//
// Created by FabianKlaffenboeck on 08/04/2024.
//

#ifndef SURRON_ULTRABEEFIRMWARE_ASYNCGPSHANDLER_H
#define SURRON_ULTRABEEFIRMWARE_ASYNCGPSHANDLER_H

#endif //SURRON_ULTRABEEFIRMWARE_ASYNCGPSHANDLER_H
